### PR TITLE
Fix specs around sprintf testing

### PR DESCRIPTION
**Pull request by andrewvc**
This fixes a spec failure in #16 that wasn't caught because jenkins isn't putting test results into PRs correctly.

### CODE REVIEW

**Comment by jordansissel** [comment]
Tests :+1:. Code LGTM

Confirmed that before this patch, one spec fails, and after this patch, specs pass.

Failure before patch:

```
Failures:

  1) LogStash::Outputs::Graphite if fields_are_metrics => true when metrics_format => ... match one key should match the generated key
     Failure/Error: expect(line).to match(/^#{expected_metric_name} 123.0 \d{10,}\n$/)
     NameError:
       undefined local variable or method `expected_metric_name' for #<RSpec::ExampleGroups::LogStashOutputsGraphite::IfFieldsAreMetricsTrue::WhenMetricsFormat::MatchOneKey:0x4201a617>
     # ./spec/outputs/graphite_spec.rb:46:in `block in (root)'
```

Tests :+1:. Code LGTM

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.
